import AppKit

/// macOS has no pasteboard-change notification, so polling `changeCount` is the
/// only option. 300ms is fast enough to feel instant and cheap enough to ignore.
@MainActor
final class ClipboardWatcher {
    private static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    private static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")

    private var timer: Timer?
    private var lastChangeCount: Int
    private let onCapture: (String, Bool) -> Void

    init(onCapture: @escaping (String, Bool) -> Void) {
        // Start from the current value so whatever is already on the pasteboard at
        // launch is not re-captured as if it were new.
        self.lastChangeCount = NSPasteboard.general.changeCount
        self.onCapture = onCapture
    }

    func start() {
        guard timer == nil else { return }
        timer = Timer.scheduledTimer(withTimeInterval: 0.3, repeats: true) { [weak self] _ in
            // Timers fire on the main run loop, so this is already main-actor work.
            self?.poll()
        }
    }

    /// Call right after writing to the pasteboard ourselves, so our own write is not
    /// captured back as a new item.
    func acknowledgeOwnWrite() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let types = pasteboard.types ?? []

        // Community convention: other clipboard tools mark content that should not
        // be recorded. Honouring it avoids feedback loops between managers.
        if types.contains(Self.transient) || types.contains(Self.autoGenerated) { return }

        guard let text = pasteboard.string(forType: .string),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        else { return }

        onCapture(text, types.contains(Self.concealed))
    }
}
