import AppKit

/// macOS has no pasteboard-change notification, so polling `changeCount` is the
/// only option. 300ms is fast enough to feel instant and cheap enough to ignore.
@MainActor
final class ClipboardWatcher {
    private static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    private static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    /// Where a copy came from, written by Chromium browsers. See `isFromPasswordManager`.
    private static let chromiumSource = NSPasteboard.PasteboardType("org.chromium.source-url")

    /// How long a change is left to settle before it is read. See `poll`.
    private static let settle: Duration = .milliseconds(50)

    /// What counts as nothing: whitespace, and the C0 control characters and DEL.
    /// Bitwarden's extension clears the clipboard in Chromium by writing a single NUL.
    /// Not `.controlCharacters`, which also holds format characters such as a
    /// right-to-left mark, and someone may well copy one of those on purpose.
    private static let empty = CharacterSet.whitespacesAndNewlines
        .union(CharacterSet(charactersIn: Unicode.Scalar(0x00)...Unicode.Scalar(0x1F)))
        .union(CharacterSet(charactersIn: "\u{7F}"))

    private let pasteboard: NSPasteboard
    private var timer: Timer?
    private var lastChangeCount: Int
    private let onCapture: (String, Bool) -> Void

    /// `pasteboard` is only ever something other than the general one in
    /// `scripts/verify-watcher.swift`, which drives this against a private pasteboard so it
    /// can check the rules without touching the real clipboard.
    init(pasteboard: NSPasteboard = .general, onCapture: @escaping (String, Bool) -> Void) {
        self.pasteboard = pasteboard
        // Start from the current value so whatever is already on the pasteboard at
        // launch is not re-captured as if it were new.
        self.lastChangeCount = pasteboard.changeCount
        self.onCapture = onCapture
    }

    func start() {
        guard timer == nil else { return }
        timer = Timer.scheduledTimer(withTimeInterval: 0.3, repeats: true) { [weak self] _ in
            // Timers fire on the main run loop, so this is already main-actor work; saying
            // so is what the compiler needs to see it.
            MainActor.assumeIsolated { self?.poll() }
        }
    }

    /// Call right after writing to the pasteboard ourselves, so our own write is not
    /// captured back as a new item.
    func acknowledgeOwnWrite() {
        lastChangeCount = pasteboard.changeCount
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Not private so the verification script can call it at the one instant a timer
    /// cannot be relied on to hit: between two steps of a single write.
    func poll() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count

        // A writer puts its types on the pasteboard one call at a time, and only the first
        // call — emptying it — moves `changeCount`. Bitwarden's desktop app writes the text
        // and then, separately, the concealed marker; Chromium writes the text and then the
        // type saying where the copy came from. A read in between takes a secret for
        // ordinary text, and a read straight after the emptying finds nothing and loses the
        // copy altogether. A moment's wait lets the writer finish; a change replaced by
        // then is left to the next poll, and nothing is read once the watcher is stopped.
        Task { @MainActor [weak self] in
            try? await Task.sleep(for: Self.settle)
            guard let self, self.timer != nil, self.pasteboard.changeCount == count else { return }
            self.read(count)
        }
    }

    private func read(_ count: Int) {
        let types = pasteboard.types ?? []

        // Community convention: other clipboard tools mark content that should not
        // be recorded. Honouring it avoids feedback loops between managers.
        if types.contains(Self.transient) || types.contains(Self.autoGenerated) { return }

        guard let text = pasteboard.string(forType: .string),
              !text.trimmingCharacters(in: Self.empty).isEmpty
        else { return }

        let secret = types.contains(Self.concealed)
            || pasteboard.string(forType: Self.chromiumSource).map(Self.isFromPasswordManager) == true

        // Each read above asks the pasteboard afresh, so a write landing between them would
        // pair one copy's text with another's marks. Checked again after the reads, that
        // copy is left for the next poll to read whole.
        guard pasteboard.changeCount == count else { return }
        onCapture(text, secret)
    }

    /// Whether a copy's recorded source is a password manager's browser extension.
    ///
    /// Browsers give their extensions no way to mark a copy as secret, so this is the only
    /// sign a password copied from one carries. Chromium records the full URL of the page
    /// a copy was made on; only the ID is taken from it and nothing is kept, because a web
    /// page's path and query can hold anything. Parsed by hand rather than with
    /// `URLComponents`: only the start of the string matters, and how `URLComponents`
    /// treats stray characters further along is not documented for every macOS release
    /// this runs on — a URL it refused would show a secret in full.
    ///
    /// It recognises copies made on the extension's own pages. One made by an extension's
    /// menu inside a web page is credited to that page, and Safari and Firefox cannot say
    /// which extension copied. See `PasswordManagerExtensions`.
    nonisolated static func isFromPasswordManager(_ source: String) -> Bool {
        let scheme = "chrome-extension://"
        let url = source.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        guard url.hasPrefix(scheme) else { return false }
        let id = url.dropFirst(scheme.count).prefix { !"/?#:".contains($0) }
        return PasswordManagerExtensions.ids.contains(String(id))
    }
}
