import AppKit

// Reports what a source app marks its clipboard writes with. Deliberately never
// prints the content — only the type identifiers and a character count — because the
// whole point is to run it while copying real passwords.

let conventions = [
    "org.nspasteboard.ConcealedType": "CONCEALED (treat as secret)",
    "org.nspasteboard.TransientType": "transient (do not store)",
    "org.nspasteboard.AutoGeneratedType": "auto-generated (do not store)",
]

let seconds = Double(CommandLine.arguments.dropFirst().first ?? "90") ?? 90
let pasteboard = NSPasteboard.general
var lastChange = pasteboard.changeCount
let deadline = Date().addingTimeInterval(seconds)

print("watching the pasteboard for \(Int(seconds))s — copy a password now")
print("(content is never printed)\n")
fflush(stdout)

while Date() < deadline {
    if pasteboard.changeCount != lastChange {
        lastChange = pasteboard.changeCount
        let types = (pasteboard.types ?? []).map(\.rawValue)
        let length = pasteboard.string(forType: .string)?.count ?? 0

        let flags = conventions.keys.filter { types.contains($0) }
        print("--- change #\(lastChange) — \(length) characters ---")
        print("  marked: \(flags.isEmpty ? "nothing — would be stored like any other text" : flags.map { conventions[$0]! }.joined(separator: ", "))")
        print("  all types present:")
        for t in types.sorted() { print("    \(t)") }
        print("")
        fflush(stdout)
    }
    usleep(200_000)
}
print("done")
